spring:
  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

    database: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  datasource:
    url: "jdbc:h2:~/test"
    username: "sa"
    password: ""
